### ISSUE TITLE
Random binomial

### ISSUE THREAD

**Issue by lohedges** [metawards/MetaWards#1]
Stupid question, but can we not simply use numpy.random.binomial. Perhaps the issue is that we need the same random number generator in the C and Python code so that we can compare the outputs. If so, is it possible to use std::binomial_distribution, for which we could write our own simple Python wrapper? (Obviously this is from C++11, but no reason why we can't use it and compile the C code with g++.)

**Comment by chryswoods** [comment]
Yes, I needed to exactly match the random binomial generator in the C code. Now I’ve done that, I’ve extracted the Numpy C code and will on Sunday link that to the metadynamics C code. This will be in the extract_gsl branch. Once I’ve got agreement again between both codes I will pull back into devel. Then no need for pygsl or Numpy :-) 

(Numpy ran binomial is also really slow compared to linking properly in the C code as I avoid having to convert back and forth between ints and pyobjects in Cython. Difference is nanoseconds per random number versus microseconds - you can see this using timeit on the comparison in test_ran_binomial)

**Comment by lohedges** [comment]
Ah great. Glad it was easy to extract the Numpy C code. That makes life much easier.

**Comment by chryswoods** [comment]
I've created a new release (0.3.1) which includes switching the original C code to use the numpy ran_binomial. Both C and Python give the same answers in the same time. Have updated the GitHub action to remove gsl and pygsl. Still need numpy for testing as I generate and compare the first 1000 random numbers.

**Comment by peteroupc** [comment]
I should note that the legacy `numpy.random.binomial`'s algorithm "uses numerical inversion if the parameters are sufficiently small. This may be too much work if p = 0.5, since random bits rather than random doubles could have been used instead in the binomial generator."  This is what I have noted in a [Stack Overflow question](https://stackoverflow.com/questions/55973226/are-numpy-binomial-random-numbers-inefficient/55978965#55978965).  There may be faster ways to generate binomial random numbers in certain cases, such as a recursive algorithm mentioned in L. Devroye's work from 1986; see my [section on it](https://peteroupc.github.io/randomfunc.html#Binomial_Distribution_Optimization_for_Many_Trials).

**Comment by chryswoods** [comment]
Thanks :-)

Yes, you’re right that this could be faster. Interestingly the version I extracted and then modified is quicker than numpy, because, I think, it is calling mt19937b directly rather than through a function pointer (and is also all compiled together, giving more scope for link optimisations).

An algorithm change, as you suggest, is the next thing to speed up once I’ve finished parallelising the top-level code algorithm. If profiling shows that I need to speed up the random number generator further than I’ll code up a C version of the algorithm you suggest to drop-in replace, and also switching the basic mt19937b with a faster vectorised uniform generator.

Thanks again :-)
