### ISSUE TITLE
Build errors when trying to compile latest documentation

### ISSUE THREAD

**Issue by fentonscode** [metawards/MetaWards#111]
**Description**

Trying to build with Sphinx results in the following error for some of the code modules:

<pre>
WARNING: autodoc: failed to import function 'redirect_output' from module 'metawards.utils'; the following exception was raised:
Traceback (most recent call last):
  File "\python37\lib\site-packages\sphinx\util\inspect.py", line 225, in safe_getattr
    return getattr(obj, name, *defargs)
AttributeError: module 'metawards.utils' has no attribute 'redirect_output'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "\python37\lib\site-packages\sphinx\ext\autodoc\importer.py", line 193, in import_object
    obj = attrgetter(obj, attrname)
  File "\python37\lib\site-packages\sphinx\ext\autodoc\__init__.py", line 290, in get_attr
    return autodoc_attrgetter(self.env.app, obj, name, *defargs)
  File "\python37\lib\site-packages\sphinx\ext\autodoc\__init__.py", line 1556, in autodoc_attrgetter
    return safe_getattr(obj, name, *defargs)
  File "\python37\lib\site-packages\sphinx\util\inspect.py", line 241, in safe_getattr
    raise AttributeError(name)
AttributeError: redirect_output

WARNING: autodoc: failed to import function 'safe_eval_float' from module 'metawards.utils'; the following exception was raised:
Traceback (most recent call last):
  File "\python37\lib\site-packages\sphinx\util\inspect.py", line 225, in safe_getattr
    return getattr(obj, name, *defargs)
AttributeError: module 'metawards.utils' has no attribute 'safe_eval_float'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "\python37\lib\site-packages\sphinx\ext\autodoc\importer.py", line 193, in import_object
    obj = attrgetter(obj, attrname)
  File "\python37\lib\site-packages\sphinx\ext\autodoc\__init__.py", line 290, in get_attr
    return autodoc_attrgetter(self.env.app, obj, name, *defargs)
  File "\python37\lib\site-packages\sphinx\ext\autodoc\__init__.py", line 1556, in autodoc_attrgetter
    return safe_getattr(obj, name, *defargs)
  File "\python37\lib\site-packages\sphinx\util\inspect.py", line 241, in safe_getattr
    raise AttributeError(name)
AttributeError: safe_eval_float

looking for now-outdated files... none found
pickling environment... done
checking consistency... \MetaWards\doc\source\api\generated\metawards.utils.redirect_output.rst: WARNING: document isn't included in any toctree
\MetaWards\doc\source\api\generated\metawards.utils.safe_eval_float.rst: WARNING: document isn't included in any toctree
done
preparing documents... done
</pre>

**Environment:**
 - OS: Windows 10 x64
 - Python: 3.7.4
 - Version: metawards 1.0.0+2.g5b95bf4b

**Comment by chryswoods** [comment]
Sphinx caches things between builds. While good for speed, this can cause errors when functions change name or location (e.g. after a git pull). You need to clear out the doc directory and run again. Easiest way to do this is remove the doc directory completely and then “git checkout doc”

**Comment by fentonscode** [comment]
Hi @chryswoods , I've just completely reset everything (delete, re-clone etc..) and I am getting the same error. I have got the latest tags and building from source at 1.1.0

**Comment by chryswoods** [comment]
There is still a cache somewhere on your system from an old version of MetaWards, or Sphinx is finding an old version installed from which it is reading the list of functions/classes to build (they are listed in the `__init__.py` files. The errors are because sphinx can't find "save_eval_float" and "redirect_output" from metawards.utils. Both of these functions were removed from metawards.utils a while back, I think before version 1.0. Somewhere on your system sphinx is finding an instruction to import these functions, despite them not existing, hence the import error. Make sure that your installed MetaWards version is the same as the version in GitHub, e.g. run "pip install ." in your GitHub directory.

You should be able to see the version that Sphinx found as it is printed at the top of the output when building, e.g. below the "Running Sphinx v1.8.0" you should see lines saying "repository = https://github.com/metawards/MetaWards" and "version = 1.1.0 : RELEASE = 1.1.0". If you don't see the 1.1.0 version and RELEASE then Sphinx is finding an older version on your machine.

I've searched through all files in metawards 1.1.0 and there is no reference to safe_eval_float or redirect_output. I have just successfully built the docs in my Windows 10 VM using the winbuild.bat script, so I think this is a configuration error on your system.

**Comment by fentonscode** [comment]
I've definitely got the metawards version I should have, so I will have to see where Sphinx is holding a cache, perhaps in the Python environment package folders?

**Comment by chryswoods** [comment]
Look for files on your disk that contain "safe_eval_float". There should be none, as this function has been removed now.

**Comment by chryswoods** [comment]
Thanks - I'll close this now as I don't think this is a MetaWards issue. Please feel free to re-open if I am wrong :-)
