### ISSUE TITLE
Importing extract_default into a custom extractor ignores custom code

### ISSUE THREAD

**Issue by fentonscode** [metawards/MetaWards#59]
**Description**
If a custom extractor imports extract_default in order to append new outputs to the default outputs, then the build step ignores the rest of the Python code after the import statement.

**To Reproduce**

`get_i_per_ward.py`
<pre>
from metawards.extractors._extract_default import extract_default

def extract_get_i_per_ward(**kwargs):
    print("Sending I per ward to the output stream")
    return extract_default(**kwargs) + [my_custom_output]
</pre>

Call MetaWards with "--extractor get_i_per_ward" option.
All statements after the import are ignored (by checking output you can see that the function body, including the print statement, is ignored). Console output shows building the default extractor only. 

Removing the import and call to extract_default causes the expected results from my_custom_output to be present in the output (but without the defaults)

**Expected behavior**
Extractor default MetaFunction list extended with a reference to my_custom_output
Output as default output + output operations from my_custom_output

**Screenshots**
![extract](https://user-images.githubusercontent.com/8965253/81507202-a881ab80-92f3-11ea-9615-619e7f9006bf.png)

**Environment (please complete the following information):**
 - OS: Windows 10
 - Python: 3.7.4
 - Version: metawards 0.10.0

**Comment by fentonscode** [comment]
Addendum: This may also affect _extract_large (unverified)

**Comment by chryswoods** [comment]
This is because you have imported "extract_default" into your custom extractor. This means that extract_default is the first function that is named as "extract_something", so that this is used instead of the function you want. You need to write;

```python
def extract_get_i_per_ward(**kwargs):
    from metawards.extractors._extract_default import extract_default
    print("Sending I per ward to the output stream")
    return extract_default(**kwargs) + [my_custom_output]
```

I'll add a warning to the tutorial to say that you can't import functions into the global namespace.

**Comment by chryswoods** [comment]
Or you could write

```python
from metawards.extractors._extract_default import extract_default as _extract_default

def extract_get_i_per_ward(**kwargs):
    print("Sending I per ward to the output stream")
    return _extract_default(**kwargs) + [my_custom_output]
```

**Comment by fentonscode** [comment]
@chryswoods Thanks, I was unaware it was set up that way, do you also need the __all__ attribute? The pre-defined extractors have this.

**Comment by chryswoods** [comment]
No - the all attribute is something that is used when building a module to say which symbols should be exported. It is a bit like dllexport for C or C++.

**Comment by fentonscode** [comment]
No problem, I was just making sure there were no side-effects from not having the exports. Thanks for demonstrating the usage.

**Comment by chryswoods** [comment]
Re-opening as I've given it some thought and this behaviour is very confusing. A simple fix would be for me to use the last function in a file that is called "extract_XXX" rather than the first. This would mean your original custom extractor would work. I will create a fix branch and will implement this for all of the plugin interfaces, and will re-close this issue once that fix has been tested and pulled back into devel.

Speaking of devel, last night I released 0.11.0. You will need to update to this version if you want to do part 5 of the tutorial (multiple demographics and shielding)

**Comment by fentonscode** [comment]
@chryswoods what about having a base class that a user can inherit an extractor interface from? That feels like a more natural polymorphic step, although maybe not the most common in Python.

**Comment by chryswoods** [comment]
The python way to do this is to use functions and duck-typing. Polymorphism is not pythonic. It would also add a layer of complexity to new users who would have to understand polymorphism before they could write a new plugin. Now, they just write a function and the only new concept is kwargs.

**Comment by fentonscode** [comment]
I thought that would be the case, it felt wrong doing it in Python like that with a different project, but from a C/C++ background it was my first instinct. Thanks for looking in to this!
