### ISSUE TITLE
Custom iterators and extractors failing to build

### ISSUE THREAD

**Issue by fentonscode** [metawards/MetaWards#80]
**Description**
Default definitions are overwriting custom functions as in #59 again if imports are not in local scope.

**To Reproduce**
See #59 for details

**Environment (please complete the following information):**
 - OS: Windows 10 x64
 - Python: 3.7.4
 - Version: MetaWards 0.12.0

**Comment by chryswoods** [comment]
I've tried this on my machine and it works as it should. This suggests that something different and unexpected is happening on Windows. I'll create unit test around this, but could you run the below script and let me know what is output?

```python
from metawards.extractors import build_custom_extractor

extractor = "get_i_per_ward"

func = build_custom_extractor(extractor)

print(func)
```

**Comment by chryswoods** [comment]
I apologise - I've now hit the same issue myself, and it has thrown up that my understanding of the internals of Python was wrong. I thought that the functions were listed in order or definition, but Python actually lists them internally in alphabetical order! This meant that my tests for me worked, by chance, as alphabetically my iterator was the last. However, for you, it fails as your iterators are alphabetically first.

I am working on a fix based on choosing the iterator that is defined in the file, rather than the one that is imported.

**Comment by chryswoods** [comment]
Solved in the linked PR. This issue will be closed automatically once merged.
