### ISSUE TITLE
Inconsistent iterators and extractors in running ensembles

### ISSUE THREAD

**Issue by fentonscode** [metawards/MetaWards#82]
**Describe the bug**
After a lengthy ensemble run it appears that some run folders have fallen back to the default iterators and extractors silently.

Succeeded: [Example](https://github.com/UQ4covid/data/tree/master/metawards/initial_ensemble/raw_outputs/0i678788v0i678788v0i237936v1i0v0i342306v0i579123v0i508621x001)
Failed: [Example](https://github.com/UQ4covid/data/tree/master/metawards/initial_ensemble/raw_outputs/0i998304v0i998304v0i178371v1i0v0i505529v0i899042v0i763058x001)

**Reproduction**
See the run commands and setup [here](https://github.com/UQ4covid/data/tree/master/metawards/initial_ensemble) - Note that the readme is slightly behind, but runscript has steps (all generated files are present)

**Expected behavior**
Runs with a design input should use the same extractor and iterator

**Environment (please complete the following information):**
 - OS: Windows 10 x64
 - Python: 3.7.4
 - Version: 0.12.0+15.g60d83419

**Comment by chryswoods** [comment]
This is now (hopefully!) fixed in the PR that is going into devel now. The build_custom_XXX functions now check to import only functions that are defined in the custom python script, and not functions imported from metawards. This issue will close automatically once the PR has been merged into devel.
