### ISSUE TITLE
Documentation on extractor stage handling is incomplete

### ISSUE THREAD

**Issue by fentonscode** [metawards/MetaWards#98]
**Description**

When designing an extractor to handle different stages of the analysis, modifying the extractor signature to accept the `stage` positional argument causes cascading errors in output functions by reporting that positional arguments are missing. There is no clear example on how to do per-stage behaviour.

Copying the behaviour within the default extractor leads to the problem above, which requires significant redesigning of all functions used within the extract and output stages. This also requires significant copy and paste of code, which is error prone. 

**Example** signature `def extract_my_function(stage: str, **kwargs):` causes problems with positional arguments missing in several output functions

Attempting to extract the stage via the keyword arguments dictionary does not inform metawards about which stages the extractor is used on. Ultimately the parameter only ever takes the value of `analyse` - which makes initialisation methods error prone by relying on testing for day zero.

**Example** Reading from kwargs as `model_stage = kwargs["stage"]` passes no information to metawards and the stage only ever contains `analyse`. Testing for day zero will not work if the simulation is started on other dates (but can be done)

Documentation [here](https://metawards.org/api/generated/metawards.extractors.extract_custom.html#metawards.extractors.extract_custom) states that metawards can detect which stages an extractor uses but gives no methodology on how this is achieved or how to pass this information to metawards from the custom extractor.

Documentation [here](https://metawards.org/tutorial/part04/01_extractors.html) shows the signature and design for extractors accepting positional arguments, but attempting to use `stage` fails as above.

**Expected content**
Ideally:
 - A list of output stages required in a model, referenced by an example extractor that shows which functions are completed by metawards and which are expected to be performed in the extractor
 - An example of performing zero-day inits by catching the 'initialise' stage parameter which does not raise syntax errors in otherwise working extractors

**Environment:**
 - OS: Windows 10 x64
 - Python: 3.7.4
 - Version: metawards 1.0.0

**Comment by chryswoods** [comment]
I agree - this should (eventually) be documented in a tutorial. It is not yet for two reasons;

1. we follow design-by-tutorial, meaning that features are only public once they are in the tutorial, and there is a compelling use-case for them. I am still not totally sure that the "stage" behaviour needs to be publicly visible. Once I have a good tutorial example that needs it, then I will write the tutorial and make it public.

2. the API specifically for the setup and finalise stages is not yet fixed, so I don't want to commit to writing a tutorial for these as they may change. Our versioning scheme would mean that, once they were in a tutorial, we'd have to support the old API if we change it (which is likely). The metawards module and tutorials form the public API, while metawards.utils (which is where the stage behaviour is) doesn't have this backwards compatibility guarantee.

If I remember correctly you wanted to look at the stage (and I originally suggested stage) because you need to initialise some data (or database connections) on first load. A good way to do this now is to follow this tutorial - https://metawards.org/tutorial/part04/01_extractors.html#exiting-early

Here the start time is obtained at the point of first run by looking to see if network.params has the "_start_model_time" attribute. If it doesn't, then setup code is run (get the current time). This is a good pattern for running setup for an extractor. Just put the setup data into a new attribute on network.params if it doesn't exist there already. The code guarantees to clear network.params between runs, so any code that checks for network.params._your_custom_attribute is guaranteed to run only once at the beginning of the run.

I hope that this makes sense. For completeness, even though I don't recommend this approach, here is a custom extractor that can do different things at different stages (always returns "extract_default(stage)" so that the default actions happen at each stage)

```python
from metawards.extractors import extract_default
from metawards.utils import Console


def extract_stage(stage, **kwargs):
    Console.print(f"I am running at stage {stage}")

    if stage == "setup":
        Console.print("My custom setup code")
    

    return extract_default(stage=stage, **kwargs)
```

**Comment by fentonscode** [comment]
Hi @chryswoods , thanks foe picking this up. During the port to HPC I am moving into a managed database system to remove the need for post-processing in our uses. I can provide an example extractor and some documentation when it's done if that would be useful?

**Comment by fentonscode** [comment]
Something to consider with the example you have given is that if you move to a custom output function then as per my original post, there are specific positional arguments that are required in my build. As an example: the utility function `call_function_on_network` will complain that it suddenly doesn't have enough arguments. It's not very clear why these are needed and how they should be passed properly.

**Comment by chryswoods** [comment]
Yes - it is not clear as, explained in my response to your recent issue, call_function_on_network should not be used for the setup stage. There is a completely different API for the setup stage which is not yet stable, hence not yet in the tutorial and not recommended for use. The setup stage is currently only calling setup_core (https://github.com/metawards/MetaWards/blob/3ef18524b563e0a76e68f5dfc5b1ae8f338a5115/src/metawards/extractors/_output_core.pyx#L167) which you can see has a completely different API to the foi, infect and analysis stages. This API is not stable and not in the tutorials, so I do not recommend you try to use it for your extractor. Please use the method I recommended which was to add an attribute to network.params, as shown in the tutorial. We can discuss the API next week once I am back from holiday.
